version: '2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=thinknetica_devops_production
    volumes:
      - postgres_production:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    image: konoplevroman/thinknetica_devops_app:v.1.0.0
    environment:
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
      - SECRET_TOKEN=$SECRET_TOKEN
      - DB_HOST=postgres
      - RAILS_ENV=production
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - 80:3000
    depends_on:
      - postgres

volumes:
  postgres_production:
