version: '2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=thinknetica_devops_development
    volumes:
      - postgres_development:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    environment:
      - DB_HOST=postgres
    ports:
      - 80:3000
    depends_on:
      - postgres

volumes:
  postgres_development:
